/* Generated by tools/doom/build_test_arena.py; do not edit.
 * Metadata only. Include after GameWorldTextures.h in the renderer.
 * World bank SHA256: 677e02313c955e92ac1fcc83b425be2efa7e61444e3f76b1ce2c642499bbba25
 * Wall order: STARTAN3, COMPBLUE, BROWNGRN, METAL
 * Floor=FLOOR4_8, ceiling=CEIL3_5; all texture pixels are shared. */
#pragma once

static const GameWorldSide doom_test_world_sides[4] = {
    {0,0,0u,173u,0u}, /* STARTAN3 */
    {0,0,0u,87u,0u}, /* COMPBLUE */
    {0,0,0u,80u,0u}, /* BROWNGRN */
    {0,0,0u,136u,0u}, /* METAL */
};
static const GameWorldLine doom_test_world_lines[4] = {
    {0u,65535u,0,16384},
    {1u,65535u,16384,0},
    {2u,65535u,0,-16384},
    {3u,65535u,-16384,0},
};
static const GameWorldSector doom_test_world_sectors[2] = {
    {62u,30u}, {62u,30u},
};
static const GameWorldMap doom_test_world = {
    4u,4u,2u,doom_test_world_sides,doom_test_world_lines,doom_test_world_sectors
};

#define DOOM_TEST_WORLD_BYTES (sizeof(doom_test_world_sides) + \
    sizeof(doom_test_world_lines) + sizeof(doom_test_world_sectors) + sizeof(doom_test_world))
