"""Build a bounded, flat native test arena and its own world-material metadata.

No WAD geometry is borrowed. The texture names resolve against the existing
world bank manifest, and only small literal IDs are emitted into the test
world header; DoomTestMap.c never includes the large pixel-bank header.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from build_game_maps import array, build_cells

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "System/applications/user/doom_lite"
MANIFEST = ROOT / "docs/doom-game-world.json"
X0, Y0, X1, Y1 = 0, -256, 768, 256
GRID_X, GRID_Y = X0 - 32, Y0 - 32
WIDTH, HEIGHT = (X1 - X0) // 32 + 2, (Y1 - Y0) // 32 + 2
WALL_NAMES = ("STARTAN3", "COMPBLUE", "BROWNGRN", "METAL")
FLOOR_NAME, CEILING_NAME = "FLOOR4_8", "CEIL3_5"


def cells_for(lines):
    """Both sides of grid-aligned walls need a closed-cell supercover.

    Padding retains the wall in the next DDA interval if fixed-point cell
    distance rounding puts an exact outer-boundary intersection just beyond
    the previous interval. Tiny BSP outside leaves make this padding solid.
    """
    rows, cells, refs = build_cells(lines, (GRID_X, GRID_Y), (WIDTH, HEIGHT))
    assert len(rows) == HEIGHT + 1 and all(0 <= r < 4 for r in refs)
    # Verify every wall coordinate sampled in the interior-adjacent cell.
    indexed = {(cell[0], gy): refs[cell[1]:cell[1] + cell[2]]
               for gy in range(HEIGHT)
               for cell in cells[rows[gy]:rows[gy + 1]]}
    for i, line in enumerate(lines):
        x1, y1, x2, y2, *_ = line
        for step in range(65):
            x, y = x1 + (x2 - x1) * step // 64, y1 + (y2 - y1) * step // 64
            gx, gy = (x - GRID_X) // 32, (y - GRID_Y) // 32
            assert i in indexed[(gx, gy)], (i, x, y)
    return rows, cells, refs


def material_ids():
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    materials = {(m["kind"], m["name"]): m for m in manifest["materials"]}
    walls = []
    for name in WALL_NAMES:
        material = materials[("wall", name)]
        assert material["output_transparent_pixels"] == 0, name
        walls.append(material["id"])
    flats = [materials[("flat", name)]["id"] for name in (FLOOR_NAME, CEILING_NAME)]
    return walls, flats, manifest["header_sha256"]


def generate_map():
    # Clockwise walls put the room on each linedef's front/right side.
    lines = [(X0, Y0, X0, Y1, 1, 0, 0, 0, 65535),
             (X0, Y1, X1, Y1, 1, 0, 0, 0, 65535),
             (X1, Y1, X1, Y0, 1, 0, 0, 0, 65535),
             (X1, Y0, X0, Y0, 1, 0, 0, 0, 65535)]
    things = [(128, 0, 0, 1, 2, 0)]
    things += [(352, y, 180, kind, 2, 0)
               for y, kind in zip((-90, -30, 30, 90), (3004, 9, 3001, 3002))]
    things += [(x, y, 0, kind, 2, 0) for x, y, kind in (
        (256, -48, 2001), (256, 0, 2008), (256, 48, 5),
        (384, -48, 2007), (384, 0, 2012), (384, 48, 6),
        (512, -48, 2049), (512, 0, 2048), (512, 48, 13),
        (640, -48, 2011), (640, 0, 2018), (640, 48, 2014))]
    sector = (0, 128, 224, 0, 0, 0, 0, 0, 128, 128, 0, 0, X0, Y0, X1, Y1)
    outside = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, GRID_X, GRID_Y, X1 + 32, Y1 + 32)
    # Root is last (3). Child high bit marks a subsector: room0, outside1.
    nodes = [(0,Y1,32,0,32768,32769), (0,Y0,32,0,32769,0),
             (X1,0,0,32,32769,1), (X0,0,0,32,2,32769)]
    rows, cells, refs = cells_for(lines)
    arrays = (("things", "DoomMapThing", things, True),
              ("lines", "DoomMapLine", lines, True),
              ("sectors", "DoomMapSector", [sector, outside], True),
              ("subsectors", "uint16_t", [0,1], False),
              ("row_first", "uint16_t", rows, False),
              ("cells", "DoomMapCell", cells, True),
              ("cell_refs", "uint16_t", refs, False))
    parts = ["/* Generated by tools/doom/build_test_arena.py; do not edit.",
             " * Original flat rectangular test geometry; no WAD map is reused. */",
             "#pragma once", '#include "DoomMap.h"', ""]
    parts += [array(kind, "doom_test_" + name, values, fields)
              for name, kind, values, fields in arrays]
    parts += ["static const DoomMapNode doom_test_nodes[4] = {"]
    parts += ["    {" + ",".join(str(value) for value in row[:4]) +
              ",{ " + str(row[4]) + "," + str(row[5]) + " }}," for row in nodes]
    parts += ["};", ""]
    parts += ["static const DoomMap doom_test_map = {",
              '    .name="TEST", .index=DOOM_MAP_COUNT,',
              "    .start_x=128, .start_y=0, .start_angle=0, .start_sector=0,",
              f"    .grid_x0={GRID_X}, .grid_y0={GRID_Y}, .grid_width={WIDTH}, .grid_height={HEIGHT},",
              f"    .thing_count={len(things)}, .line_count=4, .sector_count=2, .node_count=4,",
              f"    .subsector_count=2, .cell_count={len(cells)}, .cell_ref_count={len(refs)},",
              "    .things=doom_test_things, .lines=doom_test_lines, .sectors=doom_test_sectors,",
              "    .nodes=doom_test_nodes, .subsector_sector=doom_test_subsectors, .row_first=doom_test_row_first,",
              "    .cells=doom_test_cells, .cell_refs=doom_test_cell_refs,", "};", "",
              "#define DOOM_TEST_MAP_DATA_BYTES (sizeof(doom_test_map) + sizeof(\"TEST\") + \\"]
    parts += ["    sizeof(doom_test_nodes) + " + " + ".join(f"sizeof(doom_test_{name})" for name, *_ in arrays) + ")", ""]
    return "\n".join(parts)


def generate_world():
    walls, flats, source_hash = material_ids()
    parts = ["/* Generated by tools/doom/build_test_arena.py; do not edit.",
             " * Metadata only. Include after GameWorldTextures.h in the renderer.",
             f" * World bank SHA256: {source_hash}",
             " * Wall order: " + ", ".join(WALL_NAMES),
             f" * Floor={FLOOR_NAME}, ceiling={CEILING_NAME}; all texture pixels are shared. */",
             "#pragma once", "", "static const GameWorldSide doom_test_world_sides[4] = {"]
    parts += [f"    {{0,0,0u,{index}u,0u}}, /* {name} */" for name, index in zip(WALL_NAMES, walls)]
    parts += ["};", "static const GameWorldLine doom_test_world_lines[4] = {",
              "    {0u,65535u,0,16384},", "    {1u,65535u,16384,0},",
              "    {2u,65535u,0,-16384},", "    {3u,65535u,-16384,0},", "};",
              "static const GameWorldSector doom_test_world_sectors[2] = {",
              f"    {{{flats[0]}u,{flats[1]}u}}, {{{flats[0]}u,{flats[1]}u}},", "};",
              "static const GameWorldMap doom_test_world = {",
              "    4u,4u,2u,doom_test_world_sides,doom_test_world_lines,doom_test_world_sectors", "};", "",
              "#define DOOM_TEST_WORLD_BYTES (sizeof(doom_test_world_sides) + \\",
              "    sizeof(doom_test_world_lines) + sizeof(doom_test_world_sectors) + sizeof(doom_test_world))", ""]
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if checked-in arena metadata is stale")
    args = parser.parse_args()
    for name, text in (("DoomTestMapData.h", generate_map()), ("DoomTestWorld.h", generate_world())):
        path = OUTPUT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                raise SystemExit(f"stale arena header: {path}")
        else:
            path.write_text(text, encoding="utf-8", newline="\n")
        print(f"ARENA {'CHECK' if args.check else 'WRITE'} {name} sha256={hashlib.sha256(text.encode()).hexdigest()}")


if __name__ == "__main__":
    main()
