"""Extract five small Freedoom sprites as read-only packed grayscale assets.

Nibble zero is transparent; 1..15 encode black through white. The renderer
can read these directly from flash without a palette or decoded sprite heap.
The source WAD and its COPYING/CREDITS files remain in doom_port/data/.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "System/applications/user/doom_port/data/freedoom-e1m1-gba.wad"
OUTPUT = ROOT / "System/applications/user/doom_lite/E1M1Sprites.h"
SOURCE_SHA256 = "88403318cb328e42135bbe81607234f5cb781d6d95fb17a3399fd3084ec6943e"
SPRITES = ((3004, "POSSA1"), (9, "SPOSA1"), (3001, "TROOA1"),
           (3002, "SARGA1"), (5, "BKEYA0"))
GRAY = (0,) + tuple((i * 255 + 7) // 14 for i in range(15))


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def read_lumps(data: bytes) -> dict[str, bytes]:
    require(len(data) >= 12, "short WAD header")
    magic, count, directory = struct.unpack_from("<4sII", data)
    require(magic == b"IWAD", "expected converted IWAD")
    require(directory <= len(data) and count <= (len(data) - directory) // 16,
            "invalid WAD directory")
    lumps = {}
    for i in range(count):
        offset, size, raw_name = struct.unpack_from("<II8s", data,
                                                  directory + i * 16)
        require(offset <= len(data) and size <= len(data) - offset,
                f"invalid lump {i}")
        name = raw_name.rstrip(b"\0").decode("ascii")
        lumps[name] = data[offset:offset + size]
    return lumps


def decode_patch(data: bytes, *, max_width: int = 255) -> tuple[int, int, list[int | None]]:
    require(len(data) >= 8, "short patch header")
    width, height, _, _ = struct.unpack_from("<hhhh", data)
    require(0 < width <= max_width and 0 < height <= 255, "invalid sprite dimensions")
    require(8 + width * 4 <= len(data), "short patch column directory")
    pixels: list[int | None] = [None] * (width * height)
    for x in range(width):
        offset, = struct.unpack_from("<I", data, 8 + x * 4)
        require(8 + width * 4 <= offset < len(data), "invalid column offset")
        previous_top = -1
        while True:
            require(offset < len(data), "unterminated patch column")
            top = data[offset]
            if top == 255:
                break
            require(offset + 4 <= len(data), "short patch post")
            length = data[offset + 1]
            if top <= previous_top:
                top += previous_top
            previous_top = top
            require(offset + length + 4 <= len(data), "short patch post pixels")
            require(top + length <= height, "post exceeds sprite height")
            for y in range(length):
                pixels[(top + y) * width + x] = data[offset + 3 + y]
            offset += length + 4
    require(any(pixel is not None for pixel in pixels), "empty sprite")
    return width, height, pixels


def pack_pixels(pixels: list[int | None], palette: bytes) -> bytes:
    require(len(palette) >= 768, "short PLAYPAL")
    output = bytearray((len(pixels) + 1) // 2)
    for i, index in enumerate(pixels):
        if index is None:
            continue
        r, g, b = palette[index * 3:index * 3 + 3]
        gray = (r * 77 + g * 150 + b * 29) >> 8
        code = 1 + (gray * 14 + 127) // 255
        output[i // 2] |= code << ((i & 1) * 4)
    return bytes(output)


def generate(data: bytes) -> tuple[str, list[tuple[str, int, int, bytes]]]:
    digest = hashlib.sha256(data).hexdigest()
    require(digest == SOURCE_SHA256, "source WAD hash differs from verified Freedoom E1M1")
    lumps = read_lumps(data)
    assets = []
    for _, name in SPRITES:
        width, height, pixels = decode_patch(lumps[name])
        assets.append((name, width, height, pack_pixels(pixels, lumps["PLAYPAL"])))
    total = sum(len(asset[3]) for asset in assets)
    require(total <= 8192, "sprite data exceeds 8 KiB flash budget")
    lines = ["/* Generated by tools/doom/build_lite_sprites.py. Do not edit.",
             f" * Freedoom E1M1 WAD SHA-256: {digest}",
             " * Assets: doom_port/data/COPYING.txt and CREDITS.txt.",
             " * Low nibble first; zero transparent, 1..15 black through white.",
             " */", "#pragma once", "#include <stdint.h>", "",
             f"#define E1M1_SPRITE_COUNT {len(assets)}u",
             f"#define E1M1_SPRITE_BYTES {total}u", "",
             "typedef struct {", "    uint16_t thing_type;",
             "    uint8_t width, height;", "    const uint8_t *pixels;",
             "} E1M1Sprite;", "",
             "static const uint8_t e1m1_sprite_gray[16] = {",
             "    " + ", ".join(str(value) for value in GRAY) + ",",
             "};", ""]
    for name, _, _, packed in assets:
        lines.append(f"static const uint8_t e1m1_sprite_{name.lower()}[{len(packed)}] = {{")
        for i in range(0, len(packed), 16):
            lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in packed[i:i + 16]) + ",")
        lines.extend(("};", ""))
    lines.append("static const E1M1Sprite e1m1_sprites[E1M1_SPRITE_COUNT] = {")
    for (thing_type, _), (name, width, height, _) in zip(SPRITES, assets):
        lines.append(f"    {{{thing_type}u, {width}u, {height}u, e1m1_sprite_{name.lower()}}},")
    lines.extend(("};", ""))
    return "\n".join(lines), assets


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--preview-dir", type=Path)
    args = parser.parse_args()
    header, assets = generate(args.source.read_bytes())
    if args.check:
        require(args.output.read_text(encoding="ascii") == header,
                "sprite header differs; regenerate it")
    else:
        args.output.write_text(header, encoding="ascii", newline="\n")
    if args.preview_dir:
        args.preview_dir.mkdir(parents=True, exist_ok=True)
        for name, width, height, packed in assets:
            preview = bytearray(width * height)
            for i in range(len(preview)):
                code = (packed[i // 2] >> ((i & 1) * 4)) & 15
                preview[i] = GRAY[code] if code else 225
            (args.preview_dir / f"{name}.pgm").write_bytes(
                f"P5\n{width} {height}\n255\n".encode("ascii") + preview)
    print(f"Freedoom sprites: {len(assets)} patches, "
          f"{sum(len(asset[3]) for asset in assets)} packed bytes; "
          f"header {'verified' if args.check else 'generated'}")


if __name__ == "__main__":
    main()
