"""Prepare front-facing Freedoom actor animation and key patches for Game.

Source patch offsets remain in map units, so death frames stay on the floor
instead of growing back to standing height. Packed 4-bit pixels are sampled
directly from read-only storage: no decoded image or animation heap is needed.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import struct

from build_lite_sprites import decode_patch, pack_pixels, read_lumps, require

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT.parent / "Freedoom-research/extracted/freedoom-0.13.0/freedoom1.wad"
OUTPUT = ROOT / "System/applications/user/doom_lite/GameSprites.h"
SOURCE_SHA256 = "7323bcc168c5a45ff10749b339960e98314740a734c30d4b9f3337001f9e703d"
# walking, attack, pain, death; frame numbers are relative to these sequences.
FAMILIES = (
    (3004, "POSS", ("A1 B1 C1 D1", "E1 F1 E1", "G1", "H0 I0 J0 K0 L0")),
    (9, "SPOS", ("A1 B1 C1 D1", "E1 F1 E1", "G1", "H0 I0 J0 K0 L0")),
    (3001, "TROO", ("A1 B1 C1 D1", "E1 F1 G1", "H1", "I0 J0 K0 L0 M0")),
    (3002, "SARG", ("A1 B1 C1 D1", "E1 F1 G1", "H1", "I0 J0 K0 L0 M0 N0")),
)
KEYS = ((5, "BKEYA0"), (6, "YKEYA0"), (13, "RKEYA0"))
PICKUPS = ((2007, "CLIPA0"), (2048, "AMMOA0"),
           (2008, "SHELA0"), (2049, "SBOXA0"),
           (2011, "STIMA0"), (2012, "MEDIA0"),
           (2014, "BON1A0"), (2015, "BON2A0"), (2018, "ARM1A0"),
           (2013, "SOULA0"), (2019, "ARM2A0"), (8, "BPAKA0"),
           (2022, "PINVA0"), (2023, "PSTRA0"), (2025, "SUITA0"))
# Black edges and midtone detail remain distinct from the light masonry.
GRAY = (0, 12, 28, 44, 60, 78, 96, 114, 132, 150, 168, 185, 200, 214, 229, 244)


def resized_patch(patch: bytes, palette: bytes) -> tuple[int, int, int, int, int, int, bytes]:
    width, height, pixels = decode_patch(patch)
    _, _, left, top = struct.unpack_from("<hhhh", patch)
    numerator, denominator = min((32, width), (48, height),
                                  key=lambda pair: pair[0] / pair[1])
    if numerator >= denominator:
        out_w, out_h = width, height
    else:
        out_w = max(1, width * numerator // denominator)
        out_h = max(1, height * numerator // denominator)
    sampled = [pixels[min(height - 1, (y * height + height // 2) // out_h) * width
                      + min(width - 1, (x * width + width // 2) // out_w)]
               for y in range(out_h) for x in range(out_w)]
    return out_w, out_h, width, height, left, top, pack_pixels(sampled, palette)


def generate(data: bytes) -> tuple[str, list[tuple[str, tuple]]]:
    digest = hashlib.sha256(data).hexdigest()
    require(digest == SOURCE_SHA256, "source differs from Freedoom 0.13.0")
    lumps = read_lumps(data)
    names = []
    mappings = []
    for thing_type, prefix, states in FAMILIES:
        rows = []
        for state in states:
            indices = []
            for suffix in state.split():
                name = prefix + suffix
                if name not in names:
                    names.append(name)
                indices.append(names.index(name))
            rows.append(indices)
        mappings.append((thing_type, rows))
    for _, name in KEYS + PICKUPS:
        names.append(name)
    assets = [(name, resized_patch(lumps[name], lumps["PLAYPAL"])) for name in names]
    total = sum(len(asset[-1]) for _, asset in assets)
    require(total <= 48 * 1024, "actor animation exceeds 48 KiB pixel budget")
    lines = ["/* Generated by tools/doom/build_game_sprites.py. Do not edit.",
             f" * Freedoom 0.13.0 SHA-256: {digest}",
             " * Attribution: doom_port/data/COPYING.txt and CREDITS.txt.",
             " * Low nibble first, zero transparent. Patch offsets in map units.",
             " */", "#pragma once", "#include <stdint.h>", "",
             f"#define GAME_SPRITE_COUNT {len(assets)}u",
             f"#define GAME_SPRITE_BYTES {total}u", "",
             "typedef struct {", "    uint8_t width, height;",
             "    uint8_t world_width, world_height;", "    int16_t left, top;",
             "    const uint8_t *pixels;", "} GameSpriteAsset;", "",
             "typedef struct {", "    uint16_t thing_type;",
             "    uint8_t count[4];", "    uint8_t frame[4][7];",
             "} GameSpriteSequence;", "",
             "static const uint8_t game_sprite_gray[16] = {",
             "    " + ", ".join(map(str, GRAY)) + ",", "};", ""]
    for name, asset in assets:
        packed = asset[-1]
        lines.append(f"static const uint8_t game_sprite_{name.lower()}[{len(packed)}] = {{")
        for offset in range(0, len(packed), 16):
            lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in packed[offset:offset + 16]) + ",")
        lines.extend(("};", ""))
    lines.append("static const GameSpriteAsset game_sprites[GAME_SPRITE_COUNT] = {")
    for name, (width, height, world_w, world_h, left, top, _) in assets:
        lines.append(f"    {{{width}u, {height}u, {world_w}u, {world_h}u, {left}, {top}, game_sprite_{name.lower()}}},")
    lines.extend(("};", "", "static const GameSpriteSequence game_sprite_sequences[4] = {"))
    for thing_type, states in mappings:
        rows = ["{" + ", ".join(f"{index}u" for index in state) + "}" for state in states]
        lines.append(f"    {{{thing_type}u, {{{', '.join(str(len(state)) + 'u' for state in states)}}}, {{{', '.join(rows)}}}}},")
    lines.extend(("};", "", "static const uint16_t game_key_types[3] = {5u, 6u, 13u};",
                  "static const uint8_t game_key_sprites[3] = {" +
                  ", ".join(f"{names.index(name)}u" for _, name in KEYS) + "};", ""))
    lines.extend(("typedef struct { uint16_t thing_type; uint8_t sprite; } GameStaticSprite;",
                  f"#define GAME_STATIC_SPRITE_COUNT {len(KEYS + PICKUPS)}u",
                  "static const GameStaticSprite game_static_sprites[GAME_STATIC_SPRITE_COUNT] = {"))
    for thing_type, name in sorted(KEYS + PICKUPS):
        lines.append(f"    {{{thing_type}u, {names.index(name)}u}},")
    lines.extend(("};", ""))
    return "\n".join(lines), assets


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--preview-dir", type=Path)
    args = parser.parse_args()
    header, assets = generate(args.source.read_bytes())
    if args.check:
        require(args.output.read_text(encoding="ascii") == header,
                "generated actor header differs")
    else:
        args.output.write_text(header, encoding="ascii", newline="\n")
    if args.preview_dir:
        args.preview_dir.mkdir(parents=True, exist_ok=True)
        for name, asset in assets:
            width, height, *_ = asset
            packed = asset[-1]
            pixels = bytes(GRAY[(packed[i // 2] >> ((i & 1) * 4)) & 15]
                           if (packed[i // 2] >> ((i & 1) * 4)) & 15 else 237
                           for i in range(width * height))
            (args.preview_dir / f"{name}.pgm").write_bytes(
                f"P5\n{width} {height}\n255\n".encode("ascii") + pixels)
    print(f"Game sprites: {len(assets)} unique patches, "
          f"{sum(len(asset[-1]) for _, asset in assets)} packed bytes; "
          f"header {'verified' if args.check else 'generated'}")


if __name__ == "__main__":
    main()
