"""Derive a compact collision grid from the converted Freedoom E1M1 WAD.

The GBA conversion stores LINEDEFS as 56-byte line_t records with Q16.16
coordinates. A cell is solid when crossed by a one-sided or blocking line.
This is intentionally a coarse walk-through map, not Doom's sector model.
"""

from collections import deque
from pathlib import Path
import struct


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "System/applications/user/doom_port/data/freedoom-e1m1-gba.wad"
OUTPUT = ROOT / "System/applications/user/doom_lite/E1M1Grid.h"
CELL = 32
START_X, START_Y = -416, 256
LINE = struct.Struct("<iiiiIiiHHiiiiHhhh")


def lumps(data):
    magic, count, directory = struct.unpack_from("<4sII", data)
    if magic != b"IWAD":
        raise ValueError("expected converted IWAD")
    found = {}
    for i in range(count):
        offset, size, name = struct.unpack_from("<II8s", data, directory + 16 * i)
        found[name.rstrip(b"\0").decode("ascii")] = data[offset:offset + size]
    return found


def main():
    entries = lumps(SOURCE.read_bytes())
    raw = entries["LINEDEFS"]
    if len(raw) % LINE.size:
        raise ValueError("unexpected LINEDEFS record size")
    lines = []
    for at in range(0, len(raw), LINE.size):
        x1, y1, x2, y2, _, _, _, _, back, *tail = LINE.unpack_from(raw, at)
        flags = tail[-4]
        if flags & 1 or back == 0xFFFF:
            lines.append((x1 >> 16, y1 >> 16, x2 >> 16, y2 >> 16))
    if not lines:
        raise ValueError("no E1M1 blocking lines")
    xs = [x for x1, _, x2, _ in lines for x in (x1, x2)]
    ys = [y for _, y1, _, y2 in lines for y in (y1, y2)]
    gx0, gy0 = min(xs) // CELL - 1, min(ys) // CELL - 1
    width = max(xs) // CELL - gx0 + 2
    height = max(ys) // CELL - gy0 + 2
    if width > 255 or height > 255:
        raise ValueError("grid exceeds 8-bit coordinates")
    grid = bytearray(width * height)

    def mark(x, y):
        gx, gy = x // CELL - gx0, y // CELL - gy0
        if 0 <= gx < width and 0 <= gy < height:
            grid[gy * width + gx] = 1

    for x1, y1, x2, y2 in lines:
        steps = max(abs(x2 - x1), abs(y2 - y1)) // 4 + 1
        for i in range(steps + 1):
            mark(x1 + (x2 - x1) * i // steps,
                 y1 + (y2 - y1) * i // steps)

    start = (START_X // CELL - gx0, START_Y // CELL - gy0)
    if grid[start[1] * width + start[0]]:
        raise ValueError("player spawn rasterized as wall")
    queue = deque([start])
    reached = {start}
    while queue:
        x, y = queue.popleft()
        for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if (nx, ny) not in reached and 0 <= nx < width and 0 <= ny < height \
                    and not grid[ny * width + nx]:
                reached.add((nx, ny))
                queue.append((nx, ny))
    if len(reached) < 1000:
        raise ValueError("player cannot explore a meaningful part of E1M1")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for y in range(height):
        row = grid[y * width:(y + 1) * width]
        rows.append("    " + ", ".join(str(v) for v in row) + ",")
    OUTPUT.write_text(
        "/* Generated by tools/doom/build_lite_grid.py from Freedoom E1M1. */\n"
        "#pragma once\n#include <stdint.h>\n"
        f"#define E1M1_CELL {CELL}\n"
        f"#define E1M1_GX0 {gx0}\n#define E1M1_GY0 {gy0}\n"
        f"#define E1M1_WIDTH {width}\n#define E1M1_HEIGHT {height}\n"
        f"#define E1M1_START_X {START_X}\n#define E1M1_START_Y {START_Y}\n"
        "static const uint8_t e1m1_grid[E1M1_WIDTH * E1M1_HEIGHT] = {\n"
        + "\n".join(rows) + "\n};\n",
        encoding="ascii",
    )
    edge_reached = any(x in (0, width - 1) or y in (0, height - 1)
                       for x, y in reached)
    print(f"grid {width}x{height}={len(grid)} bytes; "
          f"blocking lines={len(lines)}; reachable cells={len(reached)}; "
          f"edge_reached={edge_reached}")


if __name__ == "__main__":
    main()
