if(NOT DEFINED IMAGE)
  message(FATAL_ERROR "Pass -DIMAGE=<signed System image>")
endif()
file(SIZE "${IMAGE}" IMAGE_BYTES)
math(EXPR VM_ROM_BYTES "14 * 1024 * 1024")
math(EXPR SYSTEM_PARTITION_BYTES "(160 - 31) * 128 * 1024")
if(IMAGE_BYTES GREATER VM_ROM_BYTES)
  message(FATAL_ERROR "System image ${IMAGE_BYTES} exceeds 14 MiB VM ROM")
endif()
if(IMAGE_BYTES GREATER SYSTEM_PARTITION_BYTES)
  message(FATAL_ERROR "System image ${IMAGE_BYTES} crosses flash block 160")
endif()
message(STATUS "System image ${IMAGE_BYTES} bytes fits VM ROM and System partition")
